package user;

import java.io.Serializable;

/**
 * An ID generator for the users.
 * @author Chloé
 *
 */

public class UserIDGenerator implements Serializable {
	
	/**
	 * This serial version UID has been generated by Papyrus.
	 */
	private static final long serialVersionUID = -2557421117736232615L;
	
	private static UserIDGenerator instance = null;
	private int num;
	
	private UserIDGenerator() {}
	
	/**
	 * This method returns the unique instance of the class (singleton pattern).
	 */
	public static synchronized UserIDGenerator getInstance() {
		if (instance == null) {
			instance = new UserIDGenerator();
		}
		return instance;
	}
	
	public synchronized int getNextUserID() { return num ++; }

}
