package ui.clui;

public class InvalidArgumentsException extends Exception {

	/**
	 * Generated by Papyrus
	 */
	private static final long serialVersionUID = -6423328724094549455L;
	
	@Override
	public String getMessage() {
		return "Error: could not parse arguments";
	}

}
