package controller;

public class InexistingStationIdException extends Exception {
	
	/**
	 * Generated by Papyrus
	 */
	private static final long serialVersionUID = 7313842031546783752L;
	private int stationID;

	public InexistingStationIdException(int id) {
		this.stationID = id;
	}
	
	@Override
	public String getMessage() {
		String message = "Could not find a station with id " + this.stationID;
		return message;
	}

}
