package station;

public class NoElectricBikeAvailableException extends Exception {

	/**
	 * Generated by Papyrus
	 */
	private static final long serialVersionUID = -3101773794035526661L;
	
	

}
