package station;

public class NoMechanicBikeAvailableException extends Exception {

	/**
	 * Generated by Papyrus
	 */
	private static final long serialVersionUID = -5629390867860698689L;
	

}
