package station;
/**
 * This exception is thrown when a {@code User } tries to drop a {@code Bike} in a {@code Station} but he has no ongoing {@code Ride}, meaning he is not renting any {@code Bike}.
 * @author Chloé
 *
 */
public class NoOngoingRideException extends Exception {

	/**
	 * Generated by Papyrus
	 */
	private static final long serialVersionUID = -1397588095644305919L;
	

}
