package station;

/**
 * This exception is thrown when a {@code User} tries to drop a {@code Bike} to a {@code Station} that is full.
 * @author Chloé
 *
 */
public class NoSlotAvailableException extends Exception {

	/**
	 * Generated by Papyrus
	 */
	private static final long serialVersionUID = 1314180539809951081L;

	
}
