package station;

import tools.Point;

/**
 * This exception is thrown when a Station is created on a position where there already is a Station.
 * @author Chloé
 *
 */
public class StationSamePositionException extends Exception {
	
	/**
	 * Generated by Papyrus
	 */
	private static final long serialVersionUID = -1530901007820608772L;
	private Point position;

	public StationSamePositionException(Point position) {
		super();
		this.position = position;
	}

	public Point getPosition() {
		return position;
	}

@Override
public String getMessage() {
	// TODO Auto-generated method stub
	return "Error : Could not create station because there already is a station on the position : " + position + " .";
}
	

}
