package station;

public class StationOfflineException extends Exception{

	/**
	 * Generated by Papyrus
	 */
	private static final long serialVersionUID = -8887194742052845179L;
	
	private Station s1;
	
	
	
	public StationOfflineException(Station s1) {
		super();
		this.s1 = s1;
	}



	@Override
	public String getMessage() {
		// TODO Auto-generated method stub
		return "Error : the Station : " + s1 + " is Offline, no operation possible.";
	}

}
